name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'  # Cache npm dependencies for faster builds
    
    - name: Install dependencies
      run: npm install 
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps # Install both browsers you're using
    
    - name: Run Playwright tests
      run: npx playwright test
      env:
        CI: true  # Ensures CI-specific config is used
    
    # Upload HTML report (includes screenshots and videos)
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ github.run_id }}
        path: playwright-report/
        retention-days: 30
    
    # Upload all test results (includes traces, videos, screenshots)
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-test-results-${{ github.run_id }}
        path: test-results/
        retention-days: 30

    # Optional: Add test summary to PR
    - name: Publish Test Summary
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Playwright Tests
        path: test-results/junit.xml
        reporter: java-junit